basic.showNumber(5)
basic.pause(1000)
basic.showNumber(4)
basic.pause(1000)
basic.showNumber(3)
basic.pause(1000)
basic.showNumber(2)
basic.pause(1000)
basic.showNumber(1)
basic.pause(1000)
basic.showIcon(IconNames.Square)
music.playMelody("G F G A - F E D ", 120)
basic.forever(function () {
	
})
